# Generated by Django 5.2.2 on 2025-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('processing', 'Обробляється'), ('shipped', 'Відправлено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=20),
        ),
    ]
